import Head from "next/head";
import Navigation from "../Components/Navigation";
import Hero from "../Components/Hero";
import HomeSmallCardSection from "../Components/HomeSmallCardSection";
import FeaturedProductCard from "../Components/FeaturedProductCard";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Hero />
      <HomeSmallCardSection />

      <FeaturedProductCard brands />
    </div>
  );
}
